# Numpy Library

In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
D1=np.array([1,2,3,4,5])

In [5]:
np.ndim(D1)

1

In [6]:
D2=np.array([[1,2,3],[10,20,30]])

In [7]:
np.ndim(D2)

2

In [ ]:
# List

In [ ]:
import time
l1=list(range (0,50000001))
start=time.time()
l2=l1*2
print('Time taken',time.time()-start)

In [ ]:
# Array

In [ ]:
import tim
Arr1=np.array(range(0,50000001))
start=time.time()
Arr2=Arr1*2
print('Time Taken',time.time()-start)

In [8]:
D1

array([1, 2, 3, 4, 5])

In [9]:
D1+10

array([11, 12, 13, 14, 15])

In [11]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.arange(1,10)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [29]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [32]:
N1=np.linspace(10,50,20)

In [33]:
N1.size

20

# Accessing Arrays

In [35]:
a2=np.array([[1,2,3],[10,20,30]])

In [43]:
a2

array([[ 1,  2,  3],
       [10, 20, 30]])

In [44]:
a2[0]

array([1, 2, 3])

In [45]:
a2[0,1]

np.int64(2)

In [47]:
sales=[101,504,540,650,390]

In [48]:
sales

[101, 504, 540, 650, 390]

In [51]:
sum(sales)

2185

In [1]:
import random
random.randit(1,25)

AttributeError: module 'random' has no attribute 'randit'

# The List Challenge

In [2]:
import numpy as np
import time

In [13]:
# Using List
L3=list(range(0,1000000))
start=time.time()
L4=[]
for i in L3:
    L4.append(i ** 3)
print('Time Taken -> ',time.time()-start)

Time Taken ->  0.12871599197387695


In [23]:
# Using Array
Arr3=np.array(range(0,1000000))
start=time.time()
Arr4=np.array(Arr3**3)
print('Time Taken--> ',time.time()-start)

Time Taken-->  0.004318952560424805


# 2.	Identity Matrix:

In [3]:
import numpy as np
D3=np.eye(5)
D3

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# 3.	Specific Linspace:

In [6]:
D4=np.linspace(0,50,100)

In [7]:
D4

array([ 0.        ,  0.50505051,  1.01010101,  1.51515152,  2.02020202,
        2.52525253,  3.03030303,  3.53535354,  4.04040404,  4.54545455,
        5.05050505,  5.55555556,  6.06060606,  6.56565657,  7.07070707,
        7.57575758,  8.08080808,  8.58585859,  9.09090909,  9.5959596 ,
       10.1010101 , 10.60606061, 11.11111111, 11.61616162, 12.12121212,
       12.62626263, 13.13131313, 13.63636364, 14.14141414, 14.64646465,
       15.15151515, 15.65656566, 16.16161616, 16.66666667, 17.17171717,
       17.67676768, 18.18181818, 18.68686869, 19.19191919, 19.6969697 ,
       20.2020202 , 20.70707071, 21.21212121, 21.71717172, 22.22222222,
       22.72727273, 23.23232323, 23.73737374, 24.24242424, 24.74747475,
       25.25252525, 25.75757576, 26.26262626, 26.76767677, 27.27272727,
       27.77777778, 28.28282828, 28.78787879, 29.29292929, 29.7979798 ,
       30.3030303 , 30.80808081, 31.31313131, 31.81818182, 32.32323232,
       32.82828283, 33.33333333, 33.83838384, 34.34343434, 34.84

In [8]:
D4.size

100

# 4.	Reshaping:

In [14]:
arr1=np.arange(20)

In [15]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:
newarr=arr1.reshape(4,5)
newarr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# 5.	Random Noise:

In [18]:
import random
arr2=np.random.rand(10,10)
arr2

array([[0.27323194, 0.1114608 , 0.1388863 , 0.90554681, 0.47725797,
        0.48306262, 0.89525677, 0.47737652, 0.27533167, 0.75676211],
       [0.18516995, 0.34284498, 0.69808364, 0.81385966, 0.96494106,
        0.59308101, 0.49837804, 0.33031964, 0.82527722, 0.6448368 ],
       [0.41523541, 0.88534318, 0.20826575, 0.91603887, 0.44113684,
        0.69681133, 0.39576043, 0.8209363 , 0.41014286, 0.45413456],
       [0.02315161, 0.51303989, 0.34143785, 0.40868495, 0.42668531,
        0.37426338, 0.170582  , 0.27750854, 0.81814734, 0.2370962 ],
       [0.99945667, 0.22754177, 0.37514668, 0.14878543, 0.97234814,
        0.75195173, 0.33103241, 0.50032578, 0.62794435, 0.26724794],
       [0.0900809 , 0.88738396, 0.29615139, 0.62457144, 0.35273849,
        0.5081875 , 0.67724247, 0.70214827, 0.60980046, 0.15947954],
       [0.03898301, 0.63223149, 0.3716807 , 0.73288847, 0.09635473,
        0.56961879, 0.05291391, 0.42676521, 0.43846938, 0.0072668 ],
       [0.91577015, 0.63631822, 0.5317042

# 6.	Boolean Indexing (Critical for NLP):

In [20]:
arr3 = np.array([10, 50, 20, 80, 5])

In [28]:
arr3

array([10, 50, 20, 80,  5])

In [36]:
for i in arr3:
    if i > 30:
        print (True)
    else:
        print(False)

False
True
False
True
False


In [54]:
arr4=arr3>30

In [55]:
arr4

array([False,  True, False,  True, False])

In [58]:
arr3[arr4]     #"From arr3, select only positions where arr4 is True"

array([50, 80])

# 7.	Slicing 2D Arrays:

In [60]:
arr5=np.random.rand(3,3)

In [61]:
arr5

array([[0.30065788, 0.12554912, 0.97271025],
       [0.55862127, 0.42878282, 0.48634445],
       [0.81628067, 0.67231902, 0.11768273]])

In [66]:
arr5[:,1]

array([0.12554912, 0.42878282, 0.67231902])

In [68]:
arr5[1,:]

array([0.55862127, 0.42878282, 0.48634445])

# 8.	Normalization:

In [69]:
sales = np.array([1200, 1500, 1800, 2000, 1700])

In [70]:
mean=sales.mean()

In [73]:
devi=sales.std()

In [76]:
print ((sales-mean)/devi)

[-1.61311827 -0.5132649   0.58658846  1.31982404  0.21997067]


# 9.	Horizontal/Vertical Stacking:

In [9]:
import numpy as np

arr9_1=np.array([
                [1,2,3],
                [4,5,6]
                ])
arr9_2=np.array([
                [10,20,30],
                [40,50,60]
                ])

In [10]:
print(np.hstack((arr9_1,arr9_2)))

[[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]]


In [11]:
print(np.vstack((arr9_1,arr9_2)))

[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [40 50 60]]


# 10.	Finding Extremes:

In [14]:
arr10_1=np.array([[34,77,39,61,55],[92,52,99,24,79]])

In [15]:
print(np.argmax(arr10_1))

7


# 11.	Word Vector Simulation:

In [17]:
import random
arr11_1=np.random.rand(10,300)

In [18]:
arr11_1

array([[0.81045727, 0.18076349, 0.18411615, ..., 0.38201012, 0.70542855,
        0.5052947 ],
       [0.12661085, 0.44557123, 0.89092827, ..., 0.05377426, 0.99310171,
        0.80828923],
       [0.48026848, 0.53675073, 0.60069464, ..., 0.09319371, 0.881188  ,
        0.91396604],
       ...,
       [0.7968672 , 0.30269818, 0.46367506, ..., 0.42498805, 0.47258046,
        0.22748754],
       [0.73550673, 0.49440291, 0.726032  , ..., 0.87778947, 0.44630896,
        0.37432699],
       [0.61786698, 0.3806397 , 0.58934684, ..., 0.49923606, 0.56012578,
        0.12331827]], shape=(10, 300))

In [32]:
mean_row=(arr11_1.mean(0))

In [33]:
print(np.shape(mean_row))

(300,)


# 12.	Binary Transformation: 

In [42]:
arr12_1=np.array([[-25,39,59,-31,27,46,-72,45]])

In [51]:
arr12_2=np.where(arr12_1<=1 , 1 ,0)

In [52]:
arr12_2

array([[1, 0, 0, 1, 0, 0, 1, 0]])

# 13.	Dot Product:

In [54]:
arr13_1=([[129,342,458],[799,455,648]])
arr13_2=([[599,768],[328,762],[399,239]])

In [55]:
arr_dot=np.dot(arr13_1,arr13_2)

In [56]:
arr_dot

array([[ 372189,  469138],
       [ 886393, 1115214]])

# 14.	Saving Data:

In [57]:
arr14_1=np.random.rand(1000,1000)

In [60]:
np.save('arraynum.npy',arr14_1)

In [61]:
np.load('arraynum.npy')

array([[0.17974911, 0.24868686, 0.65452214, ..., 0.45120779, 0.79263242,
        0.9289459 ],
       [0.36853998, 0.46396292, 0.56535032, ..., 0.91595861, 0.60344335,
        0.88076049],
       [0.01959059, 0.37548278, 0.6635018 , ..., 0.16339556, 0.00929186,
        0.92811174],
       ...,
       [0.25967141, 0.34948865, 0.96782263, ..., 0.58763674, 0.06766543,
        0.85147771],
       [0.2215174 , 0.58776652, 0.51017635, ..., 0.70438413, 0.59245992,
        0.1908078 ],
       [0.75711271, 0.53364109, 0.57987458, ..., 0.86619463, 0.25843966,
        0.05705472]], shape=(1000, 1000))

# 15.	Broadcasting:

In [65]:
arr15_1=np.array([324,576,799])
arr15_2=np.array([[923,799,378],[915,313,910],[390,456,555]])

In [66]:
print(arr15_1+arr15_2)

[[1247 1375 1177]
 [1239  889 1709]
 [ 714 1032 1354]]


In [68]:
arr15_3=np.array([1,2,3])
arr15_4=np.array([[4,5,6],[10,20,30],[100,200,300]])

In [69]:
print(arr15_3+arr15_4)

[[  5   7   9]
 [ 11  22  33]
 [101 202 303]]


# 16.	Missing Data Handling

In [76]:
arr16_1=([10,20,30,5,np.nan,40,50,60])

In [77]:
print(np.sum(arr16_1))

nan


In [78]:
print(np.nansum(arr16_1))

215.0
